[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-support-chat"
version = "1.0.0"
dependencies = ["Django>=3.2", "channels>=3.0", "daphne", "asgiref", "redis"]
